### ISSUE TITLE
Question regarding Testing

### ISSUE THREAD

**Issue by RuiAAPeres** [chriseidhof/github-issues#1]
Are you thinking about using a framework like Quick, or you are happy with XCTest?

**Comment by chriseidhof** [comment]
I have not tested anything actually... and not too experienced! Sorry, I missed this question...

Any recommendations?

**Comment by chriseidhof** [comment]
Closing this for now.

**Comment by RuiAAPeres** [comment]
@chriseidhof  Sorry for giving feedback earlier. My question was a curiosity, more than anything. Right now I am using with XCTest, just to minimize the use of 3rd party.
