### ISSUE TITLE
_Nice to have_ support for 2FA

### ISSUE THREAD

**Issue by esttorhe** [chriseidhof/github-issues#5]
I just downloaded the code and tried running it; after setting up my token the app loads a view controller asking for `username` & `password`; I'm assuming those are :octocat: credentials(?) but since I have 2FA enabled it keeps failing :cry:

**Comment by chriseidhof** [comment]
Ah yeah! Well, this view controller doesn't do much, you need to set the github token... just add it in Credentials.swift. Would be great to have 2FA support, would you mind making a pull request for that?

**Comment by esttorhe** [comment]
I would love to :)

Actually I finished watching your presentation at `Swift Summit` not 1 hour ago and I thought about submitting a `PR` for this.

Will try to do so before `EOD` today or during the weekend :facepunch:

**Comment by neilpa** [comment]
FYI - you can create [personal access token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) and use that as your password. You don't actually need to support 2FA directly.

**Comment by esttorhe** [comment]
@neilpa I have set the access token

> after setting up my token the app loads a view controller 

But I found out the issue; the code in `master` has this:

``` swift
//let baseURL = NSURL(string: "https://api.github.com")!
let baseURL = NSURL(string: "http://localhost:4567")!
```

So it was trying to connect to a `dev` server; uncommenting the correct line makes it work as expected :bow: 

---

_Edit:_
I'm going to leave this issue open because I'm planning on supporting `2FA` anyways to learn more about this experiment of `Functional View Controllers`.

Feel free to :no_entry_sign: this if you want though

**Comment by chriseidhof** [comment]
Okay, I'm gonna close this, please open a PR once you start working on 2FA =)
